ECOSoft.ECOSoftWiki.MVC/Models/Wiki/NavigationTreeModel.cs
using ECOSoft.ECOSoftWiki.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ECOSoft.ECOSoftWiki.MVC.Models.Wiki
{
    public class NavigationTreeModel
    {
        public List<TreeViewModel> Branches { get; set; }
    }

    public class TreeViewModel
    {
        public TreeViewModel()
        {

        }
        public TreeViewModel(Branches b)
        {
            Branch = b;
        }
        public Branches Branch { get; set; }
    }
}

ECOSoft.ECOSoftWiki.MVC/Controllers/WikiController.cs
using ECOSoft.ECOSoftWiki.MVC.Models.Wiki;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECOSoft.ECOSoftWiki.MVC.Controllers
{
    public class WikiController : BaseController
    {
        // GET: Wiki
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NavigationTree()
        {
            List<TreeViewModel> branches = new List<TreeViewModel>();

            branches = DC.Branches.OrderBy(a => a.Name).Select(s => new TreeViewModel(s)).ToList();

            return View(branches);
        }
    }
}

ECOSoft.ECOSoftWiki.MVC/Views/Wiki/Index.cshtml
@using ECOSoft.ECOSoftWiki.MVC.Extensions
<style>
    #treeview_iframe {
        width: 250px;
        height: 100%;
        overflow: auto;
        border: 0;
        position: fixed;
        border-right: solid 4px #638473;
    }    
</style>
@using (Html.BeginForm())
{
    <table>
        <colgroup>
            <col width="250"/>
            <col width="1200" />
        </colgroup>
        <tr>
            <td><iframe src="@Url.Action("NavigationTree", "Wiki")" id="treeview_iframe"></iframe></td>
            <td></td>
        </tr>
    </table>
}

ECOSoft.ECOSoftWiki.MVC/Views/Wiki/NavigationTree.cshtml
@{
    Layout = "~/Views/Shared/_Layout_iframe.cshtml";
}
@model List<ECOSoft.ECOSoftWiki.MVC.Models.Wiki.TreeViewModel>
<style>
    .collapse {
        background-repeat: no-repeat;
        background-position: -36px -17px;
        display: inline-block;
        cursor: pointer;
    }

    .expand {
        background-repeat: no-repeat;
        background-position: -50px -17px;
        display: inline-block;
        cursor: pointer;
    }
</style>
<script type="text/javascript">
    $(document).ready(function () {
        $(".treeview li>ul").css('display', 'none'); // Hide all 2-level ul
            $(".collapsible").click(function (e) {
                e.preventDefault();
                    $(this).toggleClass("collapse expand");
                    $(this).closest('li').children('ul').slideToggle();
                    var id = $(this).attr('data-content');                    
                    if (!$(this).hasClass('collapse')) {
                        var img = $("#IMG_" + id).attr("src", "../Images/folder-horizontal-open.png");
                    } else {
                        var img = $("#IMG_" + id).attr("src", "../Images/folder-horizontal.png");
                    }
            });
        });
</script>
<div>
    <div class="treeview">
        @if (Model != null && Model.Count() > 0)
        {
            <ul>
                @TreeView.GetTreeView(Model, Model.FirstOrDefault().Branch.ParentID.Value)
            </ul>
            @*<ul>
                <li>
                    <img src="~/Images/source_code16.png"/>
                    <a href="ECOSoftWiki">ECOSoftWiki</a>
                    
                </li>
            </ul>*@
        }
    </div>
</div>